rd /s /q D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\About
rd /s /q D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\Assemblies
rd /s /q D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\Defs
rd /s /q D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\Languages
rd /s /q D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\Sounds
rd /s /q D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\Textures
xcopy About D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\About /e
xcopy Assemblies D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\Assemblies /e
xcopy Defs D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\Defs /e
xcopy Languages D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\Languages /e
xcopy Sounds D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\Sounds /e
xcopy Textures D:\Game\Steam\steamapps\common\RimWorld\Mods\Industrialisation\Textures /e